version: "3"

services:
  app:
    build: .docker/php7.4-fpm/
    restart: always
    container_name: app
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/php7.4-fpm/php.ini:/usr/local/etc/php/conf.d/local.ini

  db:
    image: mariadb:latest
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: application
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default

volumes:
  app:
    driver: local
  mysql:
    driver: local
